spring.application.name=interview.service 

server.port=8082

spring.config.import=optional:file:./.env[.properties]

spring.jpa.hibernate.ddl-auto=none
spring.data.redis.url=${REDIS_URL}
spring.mongodb.uri=${MONGO_URL}
ia.url=${IA_URL}
jobapplication.url=${JOBAPPLICATION_URL}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

jwt.internal.secret=${INTERNAL_SECRET}
jwt.secret=${SECRET}
jwt.issuer=${ISSUER}
jwt.audience=${AUDIENCE}

