spring.application.name=jobapplication.service 

server.port=8082

spring.config.import=optional:file:./.env[.properties]

spring.jpa.hibernate.ddl-auto=validate
spring.data.redis.url=${REDIS_URL}

jwt.secret=${SECRET}
jwt.issuer=${ISSUER}
jwt.audience=${AUDIENCE}

spring.data.mongodb.uri=${MONGO_URL}

debug=true